name: Java CI with Maven P8_OCR

on: #evenement
  push:
    branches: [ "master" ,"dev" ]

  pull_request:
    branches: [ "master" ,"dev" ]

jobs: #jobs
  build:

    runs-on: ubuntu-latest #contener docker
    steps:

      - name: Clone sources with checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install gpsUtil library
        run: mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar

      - name: Install rewardCentral library
        run: mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      - name: Install tripPricer library
        run: mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

      - name: Build with Maven / Generate Coverage Report # build livrable
        run: mvn -B package --file TourGuide/pom.xml

      - name: Generate Jacoco report
        run: mvn jacoco:report --file TourGuide/pom.xml

      - name: Upload Report
        uses: 'actions/upload-artifact@v4'
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/TourGuide/target/site/jacoco/jacoco.xml

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/TourGuide/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 1
          title: Code Coverage Jacoco
          update-comment: true
          pass-emoji: ':green_circle:'
          fail-emoji: ':red_circle:'


      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
